### ISSUE TITLE
New version not working!

### ISSUE THREAD

**Issue by SubbirHosain** [harry-private/my_dictionary#1] opened 2020-03-02 16:53 UTC
new version not working in chrome..

**Comment by harry-private** [comment] 2020-03-02 17:26
New version? I haven't updated this extension for three months.
**By the way, what is the problem?**

**Comment by SubbirHosain** [comment] 2020-03-02 17:28
When I try to add new dictionary using,, "Add Dictionary" button does not work.. that's it.

**Comment by harry-private** [comment] 2020-03-02 17:35
Thanks for letting me know, I will try to find and resolve the issue.

**Comment by harry-private** [comment] 2020-03-02 17:41
I am still able to successfully add new dictionaries, and I am using the latest version of Chrome:  **Version 80.0.3987.122 (Official Build) (64-bit)**

Which version of Chrome are you using?
Was this working before?

**Comment by SubbirHosain** [comment] 2020-03-02 17:47
**Same version** as you but unfortunately it's not working ! I have installed from chrome extension store. [https://prnt.sc/ragfa8](url)
I was trying to use it for first time. When I use the add button. It does not add anything..

**Comment by harry-private** [comment] 2020-03-02 17:53
Do you know that you also have to save settings after adding, or deleting, or after making some changes by clicking the **_Save Settings_** button?

**Comment by SubbirHosain** [comment] 2020-03-02 17:57
Yes I have tried both way.. now trying disabling my all other extensions..  did you install your working extension from chrome extension store?
**If yu don't mind, plz try a fresh install of the extension??**

**Comment by harry-private** [comment] 2020-03-02 18:02
Yes, I installed this from the Chrome store.
And I don't know how to help you? Can you please describe step by step how did you try to add the dictionary?

**Comment by SubbirHosain** [comment] 2020-03-02 18:06
1.First I installed it from the chrome store.
2.later I have given a title for the dictionary to be added
3. paste the url of the dictionary and tried to add using the "Add Dictionary" button
4. Again clicked on the "save settings" button.  
here is the **screenshot** of the whole process which I've followed
[Screenshot](https://prnt.sc/ragqwx)

**Comment by harry-private** [comment] 2020-03-02 18:14
Does any message pop up like **New dictionary is added please save the changes** or **Settings Saved**?

**Comment by SubbirHosain** [comment] 2020-03-02 18:15
> Does any message pop up like **New dictionary is added please save the changes** or **Settings Saved**?

It shows nothing. :/

**Comment by harry-private** [comment] 2020-03-02 18:16
Tried reinstalling it?

**Comment by SubbirHosain** [comment] 2020-03-02 18:17
> Tried reinstalling it?

many a times i have tried reinstalling.. the extension was helpful but i am unable to use it.
I think Add Dictionary button not firing.. I have tried on Firefox.. same issue goes with firefox.

**Comment by harry-private** [comment] 2020-03-02 18:19
Can you open the Console to see if there is any error shows up?

**Comment by harry-private** [comment] 2020-03-02 18:21
Also try to add a new dictionary keeping the console tab opened.

**Comment by SubbirHosain** [comment] 2020-03-02 18:23
> Can you open the Console to see if there is any error shows up?



> Also try to add a new dictionary keeping the console tab opened.

here is the result
[console output](https://prnt.sc/ragyy5)

**Comment by harry-private** [comment] 2020-03-02 18:54
I don't know what is causing this? why are the dictionaries not being loaded from the storage? but I hope I will be able to resolve that.

**Comment by SubbirHosain** [comment] 2020-03-02 18:56
> I don't know what is causing this? why are the dictionaries not being loaded from the storage? but I hope I will be able to resolve that.

Thank you for your efforts. now I'm using from the 35th commit version.. I hope you'll fix the issue and update here ..

**Comment by harry-private** [comment] 2020-03-03 07:46
I think the issue is fixed now, and I have also uploaded the updated extension, but Google takes some time ( could be days) to publish the extensions.

You can use the latest commit, but the data and settings will be overridden when you install the extension from Chrome.

**Comment by SubbirHosain** [comment] 2020-03-03 07:58
> I think the issue is fixed now, and I have also uploaded the updated extension, but Google takes some time ( could be days) to publish the extensions.
> 
> You can use the latest commit, but the data and settings will be overridden when you install the extension from Chrome.

Thanks a lot, harry

**Comment by harry-private** [comment] 2020-03-05 16:27
The extension has been published on the Chrome store, you can install it from there if you want.

**Closed as completed** 2020-03-05 16:29 UTC
